### ISSUE TITLE
Input widgets for class attributes  with type declarations as in magicgui?

### ISSUE THREAD

**Issue by VolkerH** [hanjinliu/magic-class#1]
Dear @hanjinliu ,

thanks, this looks great.

One question: is it also possible to keep input widgets for numbers, data, etc. as in magicgui
or is it currently restricted to generating buttons that trigger method calls?

Maybe these could be class attributes with a magicgu-like wrapper?

If we can set properties of the class that could be quite useful.

**Comment by hanjinliu** [comment]
Thanks for your feedback, @VolkerH !
Yes, actually I've also thought about setting class attributes via other type of widgets.
However, I'm pending the feature for a few reasons:

- You can define a kind of "setter" method to do this, like:

```python
@magicclass
class C:
    data = 0
    def set_class_attr(self, data:int):
        self.__class__.data = data
```

- I think the main reason why you want to set class attributes is to share same variants when you open multiple GUIs (otherwise you should prefer non-class attributes). In that case, you'll not often change their values so they should be set as shown in the example above.

Are there any other use cases you suppose? I know I should add some actions for class attributes, so I would be great if you have some suggestions.

**Comment by VolkerH** [comment]
Just as an example of a use case. This is something we did with magic gui:
![image](https://user-images.githubusercontent.com/2210044/132844236-6e5c2938-af9b-4e0c-9a8d-fc6a6feb7e99.png)

It allows stitching in 3 steps.
1. the user selects input files and a few other parameters and presses "Generate Preview"
2. once the previews have been generated, the user can select the correct preview from a layer drop-down list
3. the user can then trigger fusion at full resolution or generation of a Big Stitcher project.

We had to do some very hacky things to generate 3 buttons and to keep the state (which sourece tiles were loaded in the first step etc.). It is not very clean code. 

magic-class would offer a clean way to keep the state (i.e. file names of tiles, chosen symmetry transformation) and trigger different actions with different buttons. I just don't see how I can create the widgets for input such as filenames and integer with magic class. 
This is just to give you an idea for a possible use case, I don't know how feasible it would be.

**Comment by hanjinliu** [comment]
Thanks for sharing! I understood your goals.
The point is not how to make class attribute accessible. What you want may be how to keep some functions interfaces (path reader, choose layer etc. in your widget) always displayed on the main widget, while convert other functions into buttons. This feature is definitely useful in many cases! I'll consider how to make it in the later versions.

Here I can show you a temporal solution that works with `v0.1.0`.

Since classes created by `@magicclass` inherits `Container` widget, you can append/insert widgets. Magic-class supports `__post_init__` method that will be called after `__init__` (just like `dataclass`), so the simplest way is to define the loader and parameter setter with `@magicgui` and add it to magic-class (of course you can add magicgui by yourself afterword instead of defining `__post_init__`).

```python
from magicgui import magicgui
from magicclass import magicclass
from pathlib import Path

@magicclass
class C:
    def __post_init__(self):
        @magicgui(auto_call=True) # auto_call is True because we don't want to push call button every time!
        def loader(path:Path, param:int):
            self.path = path
            self.param = param
        self.insert(0, loader)

    def show_path(self):
        print(self.path)

    def show_param(self):
        print(self.param)

c = C()
c.show()
```
![図1](https://user-images.githubusercontent.com/40591297/132849853-bd0b26b0-66c4-4881-946d-436f606f0b4b.png)

**Comment by VolkerH** [comment]
Thanks for this example. This looks great, I will give it a try !
