### ISSUE TITLE
`FunctionGuiTester` and error handling

### ISSUE THREAD

**Issue by multimeric** [hanjinliu/magic-class#109]
`FunctionGuiTester` is super helpful. However what I was hoping would happen is that when I use `.call()`, it would throw an exception and thereby cause my tests to fail when it encountered an error. Instead, it seems to show the normal GUI error handler (not sure if this is QT or Napari's doing):
![image](https://github.com/hanjinliu/magic-class/assets/5019367/5d48c659-bca0-4099-bdd7-e9d37a598dce)

Is there a way to mock the error handler to make it throw an exception?

**Comment by hanjinliu** [comment]
That sounds like a bug...
Is it an exception raised inside a method?

**Comment by multimeric** [comment]
Yes, this happens when an exception is raised inside a class method. Here's a simple reproducible example. Just run `pytest test.py`:

```python
from magicclass import magicclass
from magicclass.testing import FunctionGuiTester

@magicclass
class Test:
    def load(self):
        raise Exception("Bleh")

def test_load():
    ui = Test()
    tester = FunctionGuiTester(ui.load)
    tester.call()
```

What it will do is show this error message and wait forever for user input: 
![image](https://github.com/hanjinliu/magic-class/assets/5019367/eecc9ce0-636e-4ecf-bfd7-74dc60b8108d)

What I want it to do is propagate the exception so that it fails the test suite.

**Comment by hanjinliu** [comment]
Ok, that definitely should be fixed at some points.
The dialog is a default behavior of magicclass to notify users when an error was raised in a method, only if the method is called by clicking the call button.
Since `FunctionGuiTester` emulates clicking buttons, popup dialog should be temporarily disabled.
Do you think raising an error without the dialog (as a stderr) will work in your case?

**Comment by multimeric** [comment]
> Do you think raising an error without the dialog (as a stderr) will work in your case?

I'm not exactly sure what you mean. I hope that the error remains unhandled so that pytest can see it. Printing to stderr will happen automatically but isn't my goal here.

**Comment by hanjinliu** [comment]
I mean, in my perspective, the new behavior should be "in `FunctionGuiTester.call()`, the dialog will not appear any more, but the error will be raised so that it is visible for pytest". I wonder if it should be "the dialog will still be popped up, and the error will also be visible for pytest" (I think the dialog is not needed during test but my thought may not cover some situations...).

**Comment by multimeric** [comment]
The PR looks good. I've been able to use it to hack an ad hoc way of raising exceptions. Do you need any help reviewing it to get it merged?

**Comment by hanjinliu** [comment]
Ah, sorry, I was just a bit busy doing other works.
It's ready to be merged 😅
