### ISSUE TITLE
Multi-threading without iteration numbers

### ISSUE THREAD

**Issue by SebastianHambura** [hanjinliu/magic-class#160]
Thanks a lot for your work on this tool, it's awesome :)

I was trying to implement a little class to acquire frames from a camera, and stream them to napari for some real-time visualization. I implemented a @thread_worker function that acquire some images, and with a yielded callback updated the napari layers. This works without any issues if you run for a predefined amount of frames (or time). However, I also wanted to have "live" imaging, so without end. 

In particular, I wanted to have a "start live" and a "stop live" button. I've tried with the magic-class @thread_worker, but it doesn't seem to be possible: Does your worker have a .start() and a .quit() (or similar) function ? 

I ended up implementing this for me by using napari.qt.threading.thread_worker instead.

**Comment by hanjinliu** [comment]
Hi @SebastianHambura , thank you for your question.

Because the purpose of magicclass is to remove the gap between the programming in general and GUI programming, I intentionally "hided" some of the methods specific to napari's thread_worker so that it works just like a normal method. When you clicked the button (possibly with parameters), and that's it, you just have to wait for the calculation finishes. Therefore, your code will look just like what you'll write in a non-GUI script.

In your case, a "start live" job will be a method call, and a "stop live" job will be another. Accordingly, you can use a "global" attribute to remember whether GUI is under acquisition or not. Here's a simple example:

``` python
from magicclass import magicclass
from magicclass.utils import thread_worker
import napari

@magicclass
class A:
    def __init__(self, viewer: napari.Viewer):
        self._is_recording = False
        self._viewer = viewer
        self._image_layer = viewer.add_image(np.zeros((40, 40)), name="Aquisition")
    
    def __post_init__(self):
        self._set_button_text("Start")

    @thread_worker
    def start_or_stop(self):
        if self._is_recording:
            self._is_recording = False
            self._set_button_text("Start")
        else:
            self._is_recording = True
            self._set_button_text("Stop")
            while self._is_recording:
                yield self._get_image()
                time.sleep(1)
        return
    
    @start_or_stop.yielded.connect
    def _on_yield(self, img):
        self._image_layer.data = img
    
    def _get_image(self) -> np.ndarray:
        # Just return a random image.
        # You can change this part to stream any images
        return np.random.normal(size=(40, 40))

    def _set_button_text(self, text: str):
        # self["method-name"] refers to the button of the method
        self["start_or_stop"].text = text
        
viewer = napari.Viewer()
viewer.window.add_dock_widget(A(viewer))
```

**Comment by SebastianHambura** [comment]
That seems to do the work, thanks a lot :)
