### ISSUE TITLE
cannot import click error

### ISSUE THREAD

**Issue by pr4deepr** [hanjinliu/magic-class#32]
Hi
  I installed magicclass using 
`pip install git+https://github.com/hanjinliu/magic-class.git`

When running
`from magicclass import click`

I get this error: 
`cannot import name 'click' from 'magicclass'`

It was working from the pip release, but I was getting some errors, hence the reason I installed from the updated master branch instead.

Cheers
Pradeep

**Comment by hanjinliu** [comment]
Hi @pr4deepr ,

I'm very sorry for that. I was moving `click` to another place but left the codes in an incomplete state...
I just fix it in the last commit.

However, I'm planning to relocate `click` in `magicclass.utils` because it's totally an "additional" feature (you'll get deprecation warning). Could you use `from magicclass.utils import click` instead?

**Comment by pr4deepr** [comment]
Hi @hanjinliu 
Thanks for the speedy response. 
> Could you use `from magicclass.utils import click` instead?
Yea, I'll do that. 
assuming you'll be updating your example code as well with this change, right?

Cheers
Pradeep

**Comment by hanjinliu** [comment]
Hi @pr4deepr ,

Yeah, please take a look at https://github.com/hanjinliu/magic-class/blob/main/examples/use_click.py

**Comment by pr4deepr** [comment]
Thank you!
